apiVersion: v1
kind: ConfigMap
metadata:
  name: set-dns-servers
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  by-path: data.Corefile
  by-value-regex: "(?s)(.*)forward \\. [0-9/a-zA-Z\\. ]+({.*)"
  put-value: "${1}forward . 8.8.8.8 8.8.4.4 ${2}"
