apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-cluster
spec:
  upstream:
    package: nephio-cluster-capi-kind
    repo: demo-packages
    revision: v1
  downstream:
    package: example-cluster
    repo: mgmt
  packageContext:
    data:
      siteName: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/site: example
