apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-configsync
spec:
  upstream:
    package: configsync
    repo: nephio-testorg-packages
    revision: v1
  downstream:
    package: example-configsync
    repo: mgmt-staging
