# apiVersion: config.porch.kpt.dev/v1alpha1
# kind: PackageVariant
# metadata:
#   name: xxx-configsync
# spec:
#   upstream:
#     package: configsync
#     repo: blueprint-manifests
#     revision: main
#   downstream:
#     package: xxx-configsync
#     repo: mgmt-staging