apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-repo
spec:
  upstream:
    package: nephio-repo-gitea
    repo: demo-packages
    revision: v1
  downstream:
    package: example-repo
    repo: mgmt
  packageContext:
    data:
      siteName: example
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-annotations:v0.1.4
      configMap:
        nephio.org/site: example
