apiVersion: v1
kind: ConfigMap
metadata:
  name: set-labels-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  nephio.org/site-type: edge
  nephio.org/region: us-central1
  nephio.org/site: us-central1-edge-01
  kpt.dev/deployment-environment: production
