apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coredns-caching
  namespace: example
spec:
  maxReplicas: 40
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coredns-caching
